app:
  name: Graph Maker
  version: 1.0

file:
  input_name: building2__floor1.dxf
  output_name: static/output/building2__floor1.graphml
  svg_output_name: static/output/building2__floor1.svg
  json_output_name: static/output/building2__floor1_points.json
  precision: 1

graph:
  node_size: 30.0
  scale: 1
  offset_cm: 200

layers:
  wall_layer:
    name: A-WALL
    color: "#000000"
    opacity: 0.5

  door_layer:
    name: A-DOOR
    color: "#FF0000"
    opacity: 0.5

  roof_layer:
    name: AREA-GROSS
    color: "#00FF00"
    opacity: 0.5