app:
  name: Graph Maker
  version: 1.0

file:
  input_name: waston_floor.dxf
  output_name: static/output/waston_floor.graphml
  svg_output_name: static/output/waston_floor.svg
  json_output_name: static/output/waston_floor_points.json
  precision: 1

graph:
  node_size: 30.0
  scale: 1
  offset_cm: 200

layers:
  wall_layer:
    name: A_WALL_PRTN, A_SEEN_LT, A_STRS_RAIL,A_SEEN_MD
    color: "#000000"
    opacity: 0.5

  door_layer:
    name: A_DOOR
    color: "#FF0000"
    opacity: 0.5

  roof_layer:
    name: A_ROOF
    color: "#00FF00"
    opacity: 0.5