BUILDING = '/building'

ADD_BUILDING= f'{BUILDING}/add'
BUILDING_UPDATE_DOORS_NAME = f'{BUILDING}/updateDoorsName'
BUILDING_GET_PATH = f'{BUILDING}/getPath'
BUILDING_GET_SVG_DIRECT = f'{BUILDING}/getSvgDirect'
BUILDING_GET_BUILDINGS = f'{BUILDING}/getBuildings'